In [15]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
import numpy as np
import pickle

In [16]:
df = pd.read_csv("data4.csv")

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503852 entries, 0 to 503851
Data columns (total 81 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Unnamed: 0           503852 non-null  int64
 1   time                 503852 non-null  object
 2   gen..kW.             503852 non-null  float64
 3   House.overall..kW.   503852 non-null  float64
 4   Dishwasher..kW.      503852 non-null  float64
 5   Furnace.1..kW.       503852 non-null  float64
 6   Furnace.2..kW.       503852 non-null  float64
 7   Home.office..kW.     503852 non-null  float64
 8   Fridge..kW.          503852 non-null  float64
 9   Wine.cellar..kW.     503852 non-null  float64
 10  Garage.door..kW.     503852 non-null  float64
 11  Kitchen.12..kW.      503852 non-null  float64
 12  Kitchen.14..kW.      503852 non-null  float64
 13  Kitchen.38..kW.      503852 non-null  float64
 14  Barn..kW.            503852 non-null  float64
 15  Well..kW.            503852 non-null  float64
 16  Microwave..kW.       503852 non-null  float64
 17  Living.room..kW.     503852 non-null  float64
 18  temperature          503852 non-null  float64
 19  icon                 503852 non-null  object
 20  humidity             503852 non-null  float64
 21  visibility           503852 non-null  float64
 22  summary              503852 non-null  object
 23  apparentTemperature  503852 non-null  float64
 24  pressure             503852 non-null  float64
 25  windSpeed            503852 non-null  float64
 26  cloudCover           503852 non-null  float64
 27  windBearing          503852 non-null  int64
 28  precipIntensity      503852 non-null  float64
 29  dewPoint             503852 non-null  float64
 30  precipProbability    503852 non-null  float64
 31  Furnace              503852 non-null  float64
 32  Kitchen              503852 non-null  float64
 33  Dishwasher..kW.ON    503852 non-null  int64
 34  FurnaceON            503852 non-null  int64
 35  Home.office..kW.ON   503852 non-null  int64
 36  Wine.cellar..kW.ON   503852 non-null  int64
 37  Garage.door..kW.ON   503852 non-null  int64
 38  KitchenON            503852 non-null  int64
 39  Barn..kW.ON          503852 non-null  int64
 40  Well..kW.ON          503852 non-null  int64
 41  Microwave..kW.ON     503852 non-null  int64
 42  Living.room..kW.ON   503852 non-null  int64
 43  Dia                  503852 non-null  int64
 44  Minuto               503852 non-null  int64
 45  Mes_1                503852 non-null  bool
 46  Mes_2                503852 non-null  bool
 47  Mes_3                503852 non-null  bool
 48  Mes_4                503852 non-null  bool
 49  Mes_5                503852 non-null  bool
 50  Mes_6                503852 non-null  bool
 51  Mes_7                503852 non-null  bool
 52  Mes_8                503852 non-null  bool
 53  Mes_9                503852 non-null  bool
 54  Mes_10               503852 non-null  bool
 55  Mes_11               503852 non-null  bool
 56  Mes_12               503852 non-null  bool
 57  Hora_0               503852 non-null  bool
 58  Hora_1               503852 non-null  bool
 59  Hora_2               503852 non-null  bool
 60  Hora_3               503852 non-null  bool
 61  Hora_4               503852 non-null  bool
 62  Hora_5               503852 non-null  bool
 63  Hora_6               503852 non-null  bool
 64  Hora_7               503852 non-null  bool
 65  Hora_8               503852 non-null  bool
 66  Hora_9               503852 non-null  bool
 67  Hora_10              503852 non-null  bool
 68  Hora_11              503852 non-null  bool
 69  Hora_12              503852 non-null  bool
 70  Hora_13              503852 non-null  bool
 71  Hora_14              503852 non-null  bool
 72  Hora_15              503852 non-null  bool
 73  Hora_16              503852 non-null  bool
 74  Hora_17              503852 non-null  bool
 75  Hora_18              503852 non-null  bool
 76  Hora_19              503852 non-null  bool
 77  Hora_20              503852 non-null  bool
 78  Hora_21              503852 non-null  bool
 79  Hora_22              503852 non-null  bool
 80  Hora_23              503852 non-null  bool
dtypes: bool(36), float64(28), int64(14), object(3)
memory usage: 190.3+ MB

In [18]:
df["Mes"] = df.time.str[5:7].astype(int)
df["Hora"] = df.time.str[11:13].astype(int)
df.head()

,Unnamed: 0,time,gen..kW.,House.overall..kW.,Dishwasher..kW.,Furnace.1..kW.,Furnace.2..kW.,Home.office..kW.,Fridge..kW.,Wine.cellar..kW.,...,Hora_16,Hora_17,Hora_18,Hora_19,Hora_20,Hora_21,Hora_22,Hora_23,Mes,Hora
0,0,2016-01-01 00:58:00,0.003417,0.714200,0.000033,0.021083,0.309983,0.043067,0.005167,0.123317,...,False,False,False,False,False,False,False,False,1,0
1,1,2016-01-01 00:59:00,0.003417,0.497067,0.000017,0.096983,0.062867,0.043283,0.005000,0.123283,...,False,False,False,False,False,False,False,False,1,0
2,2,2016-01-01 01:00:00,0.003450,0.465133,0.000017,0.064500,0.062633,0.043250,0.005017,0.123350,...,False,False,False,False,False,False,False,False,1,1
3,3,2016-01-01 01:01:00,0.003417,0.512933,0.000017,0.111333,0.063883,0.043300,0.004967,0.123867,...,False,False,False,False,False,False,False,False,1,1
4,4,2016-01-01 01:02:00,0.003417,0.651283,0.000017,0.114583,0.063200,0.043283,0.114167,0.124267,...,False,False,False,False,False,False,False,False,1,1

In [19]:
df.columns

Index(['Unnamed: 0', 'time', 'gen..kW.', 'House.overall..kW.',
       'Dishwasher..kW.', 'Furnace.1..kW.', 'Furnace.2..kW.',
       'Home.office..kW.', 'Fridge..kW.', 'Wine.cellar..kW.',
       'Garage.door..kW.', 'Kitchen.12..kW.', 'Kitchen.14..kW.',
       'Kitchen.38..kW.', 'Barn..kW.', 'Well..kW.', 'Microwave..kW.',
       'Living.room..kW.', 'temperature', 'icon', 'humidity', 'visibility',
       'summary', 'apparentTemperature', 'pressure', 'windSpeed', 'cloudCover',
       'windBearing', 'precipIntensity', 'dewPoint', 'precipProbability',
       'Furnace', 'Kitchen', 'Dishwasher..kW.ON', 'FurnaceON',
       'Home.office..kW.ON', 'Wine.cellar..kW.ON', 'Garage.door..kW.ON',
       'KitchenON', 'Barn..kW.ON', 'Well..kW.ON', 'Microwave..kW.ON',
       'Living.room..kW.ON', 'Dia', 'Minuto', 'Mes_1', 'Mes_2', 'Mes_3',
       'Mes_4', 'Mes_5', 'Mes_6', 'Mes_7', 'Mes_8', 'Mes_9', 'Mes_10',
       'Mes_11', 'Mes_12', 'Hora_0', 'Hora_1', 'Hora_2', 'Hora_3', 'Hora_4',
       'Hora_5', 'Hora_6', 'Hora_7', 'Hora_8', 'Hora_9', 'Hora_10', 'Hora_11',
       'Hora_12', 'Hora_13', 'Hora_14', 'Hora_15', 'Hora_16', 'Hora_17',
       'Hora_18', 'Hora_19', 'Hora_20', 'Hora_21', 'Hora_22', 'Hora_23', 'Mes',
       'Hora'],
      dtype='object')

In [20]:
df_Xy = pd.get_dummies(df, columns=["summary"], drop_first=True)

In [21]:
df_Xy = df_Xy[['gen..kW.', 'House.overall..kW.',
       'Dishwasher..kW.', 'Furnace.1..kW.', 'Furnace.2..kW.',
       'Home.office..kW.', 'Fridge..kW.', 'Wine.cellar..kW.',
       'Garage.door..kW.', 'Kitchen.12..kW.', 'Kitchen.14..kW.',
       'Kitchen.38..kW.', 'Barn..kW.', 'Well..kW.', 'Microwave..kW.',
       'Living.room..kW.', 'temperature', 'humidity', 'visibility',
       'apparentTemperature', 'pressure', 'windSpeed', 'cloudCover',
       'windBearing', 'precipIntensity', 'dewPoint', 'precipProbability',
       'Furnace', 'Kitchen', 'Dishwasher..kW.ON', 'FurnaceON',
       'Home.office..kW.ON', 'Wine.cellar..kW.ON', 'Garage.door..kW.ON',
       'KitchenON', 'Barn..kW.ON', 'Well..kW.ON', 'Microwave..kW.ON',
       'Living.room..kW.ON', 'Dia', 'Minuto', 'Mes_1', 'Mes_2', 'Mes_3',
       'Mes_4', 'Mes_5', 'Mes_6', 'Mes_7', 'Mes_8', 'Mes_9', 'Mes_10',
       'Mes_11', 'Mes_12', 'Hora_0', 'Hora_1', 'Hora_2', 'Hora_3', 'Hora_4',
       'Hora_5', 'Hora_6', 'Hora_7', 'Hora_8', 'Hora_9', 'Hora_10', 'Hora_11',
       'Hora_12', 'Hora_13', 'Hora_14', 'Hora_15', 'Hora_16', 'Hora_17',
       'Hora_18', 'Hora_19', 'Hora_20', 'Hora_21', 'Hora_22', 'Hora_23',
       'Hora', 'Mes', 'summary_Cloudy', 'summary_Other', 'summary_Rain',
       'summary_Snow']]

In [22]:
df_Xy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503852 entries, 0 to 503851
Data columns (total 83 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   gen..kW.             503852 non-null  float64
 1   House.overall..kW.   503852 non-null  float64
 2   Dishwasher..kW.      503852 non-null  float64
 3   Furnace.1..kW.       503852 non-null  float64
 4   Furnace.2..kW.       503852 non-null  float64
 5   Home.office..kW.     503852 non-null  float64
 6   Fridge..kW.          503852 non-null  float64
 7   Wine.cellar..kW.     503852 non-null  float64
 8   Garage.door..kW.     503852 non-null  float64
 9   Kitchen.12..kW.      503852 non-null  float64
 10  Kitchen.14..kW.      503852 non-null  float64
 11  Kitchen.38..kW.      503852 non-null  float64
 12  Barn..kW.            503852 non-null  float64
 13  Well..kW.            503852 non-null  float64
 14  Microwave..kW.       503852 non-null  float64
 15  Living.room..kW.     503852 non-null  float64
 16  temperature          503852 non-null  float64
 17  humidity             503852 non-null  float64
 18  visibility           503852 non-null  float64
 19  apparentTemperature  503852 non-null  float64
 20  pressure             503852 non-null  float64
 21  windSpeed            503852 non-null  float64
 22  cloudCover           503852 non-null  float64
 23  windBearing          503852 non-null  int64
 24  precipIntensity      503852 non-null  float64
 25  dewPoint             503852 non-null  float64
 26  precipProbability    503852 non-null  float64
 27  Furnace              503852 non-null  float64
 28  Kitchen              503852 non-null  float64
 29  Dishwasher..kW.ON    503852 non-null  int64
 30  FurnaceON            503852 non-null  int64
 31  Home.office..kW.ON   503852 non-null  int64
 32  Wine.cellar..kW.ON   503852 non-null  int64
 33  Garage.door..kW.ON   503852 non-null  int64
 34  KitchenON            503852 non-null  int64
 35  Barn..kW.ON          503852 non-null  int64
 36  Well..kW.ON          503852 non-null  int64
 37  Microwave..kW.ON     503852 non-null  int64
 38  Living.room..kW.ON   503852 non-null  int64
 39  Dia                  503852 non-null  int64
 40  Minuto               503852 non-null  int64
 41  Mes_1                503852 non-null  bool
 42  Mes_2                503852 non-null  bool
 43  Mes_3                503852 non-null  bool
 44  Mes_4                503852 non-null  bool
 45  Mes_5                503852 non-null  bool
 46  Mes_6                503852 non-null  bool
 47  Mes_7                503852 non-null  bool
 48  Mes_8                503852 non-null  bool
 49  Mes_9                503852 non-null  bool
 50  Mes_10               503852 non-null  bool
 51  Mes_11               503852 non-null  bool
 52  Mes_12               503852 non-null  bool
 53  Hora_0               503852 non-null  bool
 54  Hora_1               503852 non-null  bool
 55  Hora_2               503852 non-null  bool
 56  Hora_3               503852 non-null  bool
 57  Hora_4               503852 non-null  bool
 58  Hora_5               503852 non-null  bool
 59  Hora_6               503852 non-null  bool
 60  Hora_7               503852 non-null  bool
 61  Hora_8               503852 non-null  bool
 62  Hora_9               503852 non-null  bool
 63  Hora_10              503852 non-null  bool
 64  Hora_11              503852 non-null  bool
 65  Hora_12              503852 non-null  bool
 66  Hora_13              503852 non-null  bool
 67  Hora_14              503852 non-null  bool
 68  Hora_15              503852 non-null  bool
 69  Hora_16              503852 non-null  bool
 70  Hora_17              503852 non-null  bool
 71  Hora_18              503852 non-null  bool
 72  Hora_19              503852 non-null  bool
 73  Hora_20              503852 non-null  bool
 74  Hora_21              503852 non-null  bool
 75  Hora_22              503852 non-null  bool
 76  Hora_23              503852 non-null  bool
 77  Hora                 503852 non-null  int32
 78  Mes                  503852 non-null  int32
 79  summary_Cloudy       503852 non-null  bool
 80  summary_Other        503852 non-null  bool
 81  summary_Rain         503852 non-null  bool
 82  summary_Snow         503852 non-null  bool
dtypes: bool(40), float64(28), int32(2), int64(13)
memory usage: 180.7 MB

In [23]:
df_features = df_Xy[['Mes','Dia','Hora',
       'temperature',
       'humidity', 'visibility', 'apparentTemperature', 'pressure',
       'windSpeed', 'cloudCover', 'windBearing', 'precipIntensity', 'dewPoint',
       'precipProbability', 'Furnace', 'Kitchen', 'Dishwasher..kW.ON',
       'FurnaceON', 'Home.office..kW.ON', 'Wine.cellar..kW.ON',
       'Garage.door..kW.ON', 'KitchenON', 'Barn..kW.ON', 'Well..kW.ON',
       'Microwave..kW.ON', 'Living.room..kW.ON', 'Mes_2', 'Mes_3', 'Mes_4',
       'Mes_5', 'Mes_6', 'Mes_7', 'Mes_8', 'Mes_9', 'Mes_10', 'Mes_11',
       'Mes_12', 'Hora_1', 'Hora_2', 'Hora_3', 'Hora_4', 'Hora_5', 'Hora_6',
       'Hora_7', 'Hora_8', 'Hora_9', 'Hora_10', 'Hora_11', 'Hora_12',
       'Hora_13', 'Hora_14', 'Hora_15', 'Hora_16', 'Hora_17', 'Hora_18',
       'Hora_19', 'Hora_20', 'Hora_21', 'Hora_22', 'Hora_23', 'summary_Cloudy',
       'summary_Other', 'summary_Rain', 'summary_Snow']]

In [24]:
df_features = df_features.groupby(by=["Mes","Dia","Hora"]).mean().reset_index()
dates = df_features[["Mes","Dia","Hora"]]
df_features = df_features.drop(["Mes","Dia","Hora"], axis=1)

In [25]:
df_objetivos = df_Xy[['Mes','Dia','Hora',
       'gen..kW.', 'House.overall..kW.', 'Dishwasher..kW.', 'Home.office..kW.',
       'Fridge..kW.', 'Wine.cellar..kW.', 'Garage.door..kW.', 'Barn..kW.',
       'Well..kW.', 'Microwave..kW.', 'Living.room..kW.']]

In [26]:
df_objetivos = df_objetivos.groupby(by=["Mes","Dia","Hora"]).sum().reset_index().drop(["Mes","Dia","Hora"], axis=1)

In [27]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df_features)

with open('features.pkl', 'wb') as f:
    pickle.dump(scaled_data, f)

with open('objetivos.pkl', 'wb') as f:
    pickle.dump(df_objetivos, f)

with open('dates.pkl', 'wb') as f:
    pickle.dump(dates, f)